### PR TITLE
add chinese bible translation

### PR DESCRIPTION
**Pull request by wupangyen**
discussed in [PR ](https://github.com/seven1m/open-bibles/pull/28
) here

### CODE REVIEW

**Comment by seven1m** [comment]
@wupangyen thank you for your work on this. This looks good to me, but I am having trouble importing it due to some issue with Jeremiah 50:32, where MySQL gives me this error:

```
Mysql2::Error: Incorrect string value: '\\xF0\\xA4\\x8F\\xB2\\xE8\\xB5...' for column 'text' at row 1
```

I don't think this is your issue. It may have something to do with the encoding I'm using for the database column. I'll keep you posted!

**Comment by seven1m** [comment]
I found the issue! My table had used `utf8mb3` encoding, but that only supports 3-byte utf8 characters. I will get this fixed up and let you know when it's done!

**Comment by wupangyen** [comment]
> I found the issue! My table had used `utf8mb3` encoding, but that only supports 3-byte utf8 characters. I will get this fixed up and let you know when it's done!

Sounds good! I really enjoy working on this project and learning new stuff! 
so does it have to use `utf8mb4` ? I looked it up I think most traditional Chinese character are encoded in 3 bytes in UTF-8, only rare Chinese character require 4 bytes in UTF-8

Do you know If I want to try to import the file in MySQL like what you mentioned above, how should I look into to do that?

Also I want to help to put the Chinese Language on [bible-api](https://bible-api.com/), do you know where is the best place, a pull request, or repo, I can look into next to help implement it?

Thanks for taking the time Tim!

**Comment by seven1m** [comment]
The database for bible-api.com has been updated with this new translation. :tada:
 
https://bible-api.com/約翰福音+3:16?translation=cuv

Thanks for all your hard work on this!

**Pull request merged**
