### PR TITLE
added Japanese Kougo (Colloquial) OSIS data

### PR DESCRIPTION
**Pull request by bibby**
These data make heavy use of `verse/w[gloss]` to store [furigana](https://en.wikipedia.org/wiki/Furigana) for the main-line kanji (borrowed Chinese characters). These are most often printed with [ruby elements](https://en.wikipedia.org/wiki/Ruby_character).

### CODE REVIEW

**Comment by seven1m** [comment]
@bibby where was this file obtained? Where might I check that the license indicates it is free for distribution?

**Comment by bibby** [comment]
A fair question.  The source file came from [salterrae.net](http://bible.salterrae.net/en/) .
The nearby note reads:

> Those texts are based on the Colloquial Japanese Bible Published in 1954/1955 ( whose copyright is expired at 1 Jan 2006 ). Note that the texts currently available from the publisher are slightly different from those published in 1954/1955 , and their copyrights may be still active.
The most commonly used bible by the protestants in japan till the publishing of the New Interconffessional Translation (Shin-Kyoudou-yaku) in 1987.

Other precedent for its use comes from the [Sword Project](https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=JapKougo), which copied the same note.

**Comment by bibby** [comment]
Found also a [mailing list message](http://www.crosswire.org/pipermail/sword-devel/2016-January/043039.html) between the maintainer(s) of Sword and the admin at salterrae; from 2016 regarding a different version. 

This message demonstrates an awareness of and respect for previous copyrights. I think the actors as credible.

**Comment by seven1m** [comment]
Thanks!

**Pull request merged**
