### PR TITLE
Add Spanish versions

### PR DESCRIPTION
**Pull request by pablotrianda**
Hi, this PR add 4 spanish version to the file list! 

- [RV1909](https://ebible.org/details.php?id=spaRV1909)
- [SPNBES](https://ebible.org/details.php?id=SPNBES)
- [SPAPDT](https://ebible.org/details.php?id=SPAPDT)
- [VBL](https://ebible.org/details.php?id=spavbl)

cheers! :wave:

### CODE REVIEW

**Comment by seven1m** [comment]
It looks like only the first link is public domain. The other three are licensed under a Creative Commons license. Please update the readme accordingly. Thanks!

**Comment by pablotrianda** [comment]
Updated! :ok_hand:

**Comment by pablotrianda** [comment]
ok, My bad, I misunderstand the message :sweat_smile:

**Comment by pablotrianda** [comment]
Done 👍

**Comment by seven1m** [comment]
Thanks! I renamed the files to match the same format as the others and I added the license text to the README for the ones that were Creative-Commons. Thanks for getting this started... I'm very excited to have these in the collection! 🤗

**Comment by pablotrianda** [comment]
ok, perfect! Thanks you for this great project! 
cheers

**Pull request merged**
