### PR TITLE
Revert "Feature/add new language mandarin chinese"

### PR DESCRIPTION
**Pull request by seven1m**
Reverts seven1m/open-bibles#27

### CODE REVIEW

**Comment by seven1m** [comment]
@wupangyen I'm very sorry, I merged #27 blindly without checking it first. The file doesn't conform to OSIS or USFX format and doen't work with the [bible_parser](https://github.com/seven1m/bible_parser) gem. 😞 

I am reverting for now. If we can get the XML format to conform to OSIS or USFX, that would be great! And I can merge it then. Sorry for the confusion.

**Comment by wupangyen** [comment]
> @wupangyen I'm very sorry, I merged #27 blindly without checking it first. The file doesn't conform to OSIS or USFX format and doen't work with the [bible_parser](https://github.com/seven1m/bible_parser) gem. 😞
> 
> I am reverting for now. If we can get the XML format to conform to OSIS or USFX, that would be great! And I can merge it then. Sorry for the confusion.



All good! No worries! I will take some time and get the XML format to conform to OSIS or USFX!

One question after I upload the new file, how to check if it's work with the [bible_parser](https://github.com/seven1m/bible_parser) gem? Is it just by running bundle exec respec in bible_parser repo?

**Comment by seven1m** [comment]
Hmmm, great question. I'm using the import.rb script with some modifications. Let me come up with an easier way tomorrow! Thanks again.

**Comment by seven1m** [comment]
@wupangyen OK, here's a way you could test the file as a supported format:

```
gem install bible_parser
ruby -r bible_parser -e "BibleParser.new(File.open('chr-cherokee.usfx.xml')).each_verse { |v| p v }"
```

If I run that on the `chr-cherokee.usfx.xml` file, it spits out all the verses. If I run that on an unsupported file, it gives an error.

I hope that helps!

**Comment by wupangyen** [comment]
> @wupangyen OK, here's a way you could test the file as a supported format:
> 
> ```
> gem install bible_parser
> ruby -r bible_parser -e "BibleParser.new(File.open('chr-cherokee.usfx.xml')).each_verse { |v| p v }"
> ```
> 
> If I run that on the `chr-cherokee.usfx.xml` file, it spits out all the verses. If I run that on an unsupported file, it gives an error.
> 
> I hope that helps!

Thanks Tim! this is really helpful, being able to test!
Here is the [PR](https://github.com/seven1m/open-bibles/pull/29) with the new file I upload and it worked with bible_parser gem, Thanks for taking the time to look at it!
Screenshot 2024-12-26 at 12 28 10 PM

**Pull request merged**
