### PR TITLE
Added Lithuanian language Bible

### PR DESCRIPTION
**Pull request by andriuskriukas**
Source: https://www.ph4.org/_dl.php?back=bbl&a=Bible_Lithuanian_KBB&b=zefania&c

### CODE REVIEW

**Comment by seven1m** [comment]
Can you comment here with a link showing where you saw the download is public domain?

**Comment by andriuskriukas** [comment]
I know that it's publicly available to read here: https://biblijos.lt/bible/3

However, I could not find any article saying that the usage of the text is licence based. 

I found the download URL here: https://www.ph4.org/b4_mobi.php?q=zefania

**Comment by andriuskriukas** [comment]
I see in the terms and conditions that it's not allowed to sell it but I think it can be used for personal usage: https://biblijos.lt/salygos

**Comment by seven1m** [comment]
I'm sorry, this just isn't clear enough to me. The Terms of Use you linked last seems to be for the website itself, and this site hosts A LOT of bible files. There doesn't seem to be any clear information about the licensing.

There are other repositories, like [this one](https://github.com/Beblia/Holy-Bible-XML-Format), that offer just about every download, and this file would make sense there.

But this repository is for absolutely, clearly, 100% pure freely licensed and public domain works, either via explicit licensing from the translators, or because the work is so old that it predates common copyright law.

Proving the latter can be a bit difficult in my experience, but it is possible.

I'm going to close this for now, because I don't have clarity on the licensing of this file. 😢

**Comment by andriuskriukas** [comment]
Ok, makes sense. Thank you for the other repo URL! Appreciate it.

**Pull request closed without merging**
